from zoneinfo import ZoneInfo

TIMEFRAME = "1d"
BARS = 1000

TIMEZONE = ZoneInfo("Asia/Bangkok")
RUN_HOUR = 7
RUN_MINUTE = 5

SYMBOLS = [
    "BTCUSDT",
    "ETHUSDT",
    "SOLUSDT",
    "XRPUSDT",
    "DOGEUSDT",
    "BNBUSDT",
    "BCHUSDT",
    "1000PEPEUSDT",
    "ZECUSDT",
    "SUIUSDT",
    "ADAUSDT",
    "AVAXUSDT",
    "LINKUSDT",
    "FILUSDT",
    "LTCUSDT",
    "DOTUSDT",
    "UNIUSDT",
    "NEARUSDT",
    "AAVEUSDT",
    "OPUSDT",
    "APTUSDT",
    "ARBUSDT",
    "TRXUSDT",
    "HBARUSDT",
    "XLMUSDT",
]

FRACTAL_LEFT = 2
FRACTAL_RIGHT = 2

MAX_SCENARIOS = 3
MIN_RR = 1.6
MIN_CONFIDENCE_LIVE = 65.0
MIN_CONFIDENCE_BACKTEST = 55
ABC_CONFIRM_BUFFER = 0.01

MAX_RETRY = 3
