from zoneinfo import ZoneInfo

TIMEFRAME = "1d"
BARS = 1000

TIMEZONE = ZoneInfo("Asia/Bangkok")
RUN_HOUR = 7
RUN_MINUTE = 5

SYMBOLS = [
    "BTCUSDT","ETHUSDT","SOLUSDT","XRPUSDT","DOGEUSDT","BNBUSDT","BCHUSDT",
    "ZECUSDT","SUIUSDT","ADAUSDT","AVAXUSDT","LINKUSDT","FILUSDT","LTCUSDT",
    "DOTUSDT","UNIUSDT","NEARUSDT","AAVEUSDT","OPUSDT","ARBUSDT","TRXUSDT",
    "APTUSDT","HBARUSDT","INJUSDT","XLMUSDT","AXSUSDT","XMRUSDT","SNXUSDT",
    "ETCUSDT","CRVUSDT","DASHUSDT","UMAUSDT","ICPUSDT","ATOMUSDT","LPTUSDT",
    "GALAUSDT","ZILUSDT","DUSKUSDT",
]

FRACTAL_LEFT = 2
FRACTAL_RIGHT = 2

MAX_SCENARIOS = 3
MIN_RR = 1.5
MIN_CONFIDENCE_LIVE = 65.0
MIN_CONFIDENCE_BACKTEST = 65.0
ABC_CONFIRM_BUFFER = 0.01

MAX_RETRY = 3